# Generated by Django 5.2.9 on 2025-12-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogz', '0002_clientes_medicamento_pets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
